### ISSUE TITLE
Publish version 1.0.4

### ISSUE THREAD

**Issue by wendorf** [mkocher/soloist#39]
This will allow sprout-wrap to use the version that locks down chef and chef-zero to versions compatible with El Capitan's system ruby.

**Comment by aramprice** [comment]
This might need to be `'chef', '~> 12.7.0'` instead of `'~> 12.8.1'`. I just ran with the following in a `Gemfile:

``` ruby
gem 'soloist', require: false
gem 'chef', '~> 12.8.1'
gem 'chef-zero', '~> 4.5.0' 
```

And I got the same bundler error when running `soloist`

The following `Gemfile` worked fine

``` ruby
gem 'soloist', require: false
gem 'chef', '~> 12.7.0'
gem 'chef-zero', '~> 4.5.0'
```

**Comment by wendorf** [comment]
@aramprice ,

This release is intended to workaround versions 12.9.x of chef explicitly not supporting system Ruby. Although you're right that locking soloist to 12.7.x would cure they symptom of pivotal-sprout/sprout-exemplar#9, we're still not aware of the cause, so I'd prefer not to lock soloist until we know where the bundler issue is best solved.

**Comment by aramprice** [comment]
@wendorf - makes sense. I'm still not certain what exactly the root cause is.

I did notice however that this problem appeared before chef / chef-solo began declaring a `> 2.0` ruby requirement. My suspicion is that the requirement in the gem(s) was actually added after the code became incompatible with 2.0 :-/

aram

**Comment by trinitronx** [comment]
Perhaps the best bet for finding a gemset supporting system ruby 2.0 is to find the last known working chefdk distribution that used ruby 2.0, and start by locking some dependencies on the major things first (e.g.: `soloist`, `chef`, `chef-zero`, `rake`, ...), then working towards a set of gems that exhibits the least amount of bugs?

If it helps at all to know, `soloist` does work with later versions of Chef, and I've been using it periodically with different versions.  Currently, I'm using [`ruby-2.4.0` and `Chef 12.18.31` with `soloist 1.0.3`][1]

I realize that moving forward won't work easily for fresh OS X machines unless `soloist` has some other way to bootstrap itself such as `chefdk`, or it's own omnibus type install with an embedded ruby + gemset.  So there appears to be some value in getting a working gemset for system ruby 2.0.

[1]: https://github.com/trinitronx/sprout-wrap/blob/spica-local-devbox/Gemfile.lock

**Comment by aramprice** [comment]
@trinitronx I think you are correct that this is mostly about the bootstrapping problem. `soloist` is fine wth a modern ruby but if its being used to bootstrap a new machine then the gems need to support `v2.0.0` because that's what counts for ruby on macOS currently.

It might work to lock down the version of `chef` but unfortunately I think this becomes a whack-a-mole problem because most gems only indicate minimum ruby version (after introducing incompatibilities).

Related discussion here https://github.com/pivotal-sprout/sprout-wrap/issues/99
